key_admin_homepage:
    path:     /admin
    defaults: { _controller: KeyAdminBundle:Default:index }
key_admin_users:
    path:     /users
    defaults: { _controller: KeyAdminBundle:Default:users }
key_admin_pdf:
    path:     /pdf
    defaults: { _controller: KeyAdminBundle:Default:pdf }